<Window x:Class="nLogViewer.Tester.Views.ErrorWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:nLogViewer.Tester.Views"
        xmlns:fa="http://schemas.fontawesome.com/icons/"
        mc:Ignorable="d"
        Title="ErrorWindow" 
        SizeToContent="WidthAndHeight"
        ResizeMode="NoResize"
        WindowStartupLocation="CenterOwner">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="40"/>
            <RowDefinition Height="40"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal" Margin="10,0">
            <TextBlock Name="ExceptionTitle" 
               Text="В результате выполнения программы было сгенерировано исключение:" 
               Foreground="Black" 
               FontSize="14" 
               Margin="10"/>
        </StackPanel>
        <TextBlock Grid.Row="1" Name="ExceptionDescription" 
   Text="Текстовое описание ошибки" 
   TextAlignment="Center"
   Foreground="Black" 
   FontSize="14" 
   TextWrapping="Wrap"
   Margin="10"/>
        <WrapPanel Grid.Row="2" HorizontalAlignment="Right">
            <Button Name="OkBtn" IsCancel="True" MinWidth="100" Background="Red" Margin="10">Ok</Button>
        </WrapPanel>
    </Grid>
</Window>
